#!/usr/bin/env perl

use Mojolicious::Lite;
plugin toto => menu => [
   beer => {
       many => [qw/search browse create/],
       one  => [qw/view update delete/],
     },
     brewery => {
       many => [qw/find phonelist mailing_list/],
       one  => [qw/directions beers info/],
     },
     pub => {
       many => [qw/browse search map/],
       one  => [qw/info comments/],
    } ],
themeswitcher => 1;

app->start;

