#!/usr/bin/env perl

package Beer::Pub;
use Mojo::Base 'Mojolicious::Controller';
sub search {
    my $c  = shift;
    $c->render_text("now we are searching pubs from a controller class");
}

package main;
use Mojolicious::Lite;

app->routes->namespace("Beer");

get '/pub/search' => "pub/search";

get '/another/url/of/some/sort' => sub {
    my $c = shift;
    $c->stash(area => "dc");
} => "pub/map";

get '/some/url/for/info/about/a/brewery/:key' => sub {
    my $c = shift;
    my $key = $c->stash("key");
    $c->render_text("this is info about brewery $key with my own url");
} => "brewery/info";

get '/' => sub {
  my $self = shift;
  $self->stash(file => __FILE__);
  $self->render('index');
};

get '/beer/browse' => sub {
    shift->render_text("here is a page for you");
  } => "beer/browse";

plugin 'toto' =>
    menu => [
        beer => {
                   many => [qw/browse search/],
                   one => [qw/picture ingredients pubs/],
                  },
        brewery => { one => [qw/directions beers info/],
                  many => [qw/find phonelist mailing_list/] },
        pub  => { one => [qw/info comments/],
                  many => [qw/browse search map/] },
    ]
;


app->start;
__DATA__

@@ index.html.ep
% use Mojo::Asset::File;
<!doctype html><html>
  <head>
%= title 'Welcome';
</head>
  <body>
<a href=/app/>toto</a>
<hr>
<pre>
%= Mojo::Asset::File->new(path => $file)->slurp;
</pre>
  </body>
</html>
